sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - apt-transport-https

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    if [ ! -e Gemfile ]; then
      echo $PWD
      curl -s -o ./Gemfile https://raw.githubusercontent.com/salt-formulas/salt-formulas-scripts/master/Gemfile
    fi
  - bundle install

env:
    - PLATFORM=epcim/salt-formulas:saltstack-ubuntu-xenial-salt-2017.7
    - PLATFORM=epcim/salt-formulas:saltstack-ubuntu-xenial-salt-2016.3
#    - PLATFORM=epcim/salt-formulas:saltstack-ubuntu-bionic-salt-2017.7

before_script:
  - set -o pipefail
  - make test | tail
  - reno lint $PWD | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: always
    on_cancel: never   # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
